### ISSUE TITLE
[Legal ASF Brand] Full Apache project names 

### ISSUE THREAD

**Issue by michaelsembwever** [Anant/PlanetCassandra#151]
The full Apache project name must be used in titles and when first used, on every page.

The full name is "Apache Cassandra®" not the shortened "Cassandra".  Note the registered trademark symbol.

In situations where it is not possible, or does not make sense, please reach out to the Cassandra dev mailing list for clarification or an exception.

Currently on the homepage of planet cassandra this legal requirement is not being honoured.

<img width="1629" alt="Screenshot 2023-09-02 at 20 55 36" src="https://github.com/Anant/PlanetCassandra/assets/559444/c7febfa0-15d4-4cbc-a8f5-aac3b8d147ee">

**Comment by StefanVinica** [comment]
The Changes are adressed Here
https://github.com/Anant/PlanetCassandra/pull/161

**Comment by michaelsembwever** [comment]
Looks good. Thanks!
