### ISSUE TITLE
[Legal ASF Brand] Prominent link to cassandra.apache.org "Apache Cassandra" in the navigation

### ISSUE THREAD

**Issue by michaelsembwever** [Anant/PlanetCassandra#152]
In the website's navigation there needs to be a prominent link to "Apache Cassandra", linking to cassandra.apache.org

It is preferably this is in the top navigation bar.  It needs to be on every page.

**Comment by StefanVinica** [comment]
for this one i linked the apache events so that they link to cassandra.apache.org
![image](https://github.com/Anant/PlanetCassandra/assets/26149819/f7b96df3-a1df-479f-a3b2-e35703dd8a97)

**Comment by michaelsembwever** [comment]
too problems here.

1.  we need "Apache Cassandra" at the top level
2. "Apache Events" is not a trademark, and semantic is doesn't make sense. You could say "Cassandra Events", so long as "Apache Cassandra" has appeared in the page already.

**Comment by michaelsembwever** [comment]
@StefanVinica , any updates on this ?

**Comment by ramseur** [comment]
@michaelsembwever We are handling this and all other issues at the higher level project at the below link.  We will place a link in the top nav next to the contribute button.   I am going to close this issue since we no longer report here.

https://github.com/PlanetCassandra/website/issues/63
