### ISSUE TITLE
[Cassandra upstream] Remove the handbook

### ISSUE THREAD

**Issue by michaelsembwever** [Anant/PlanetCassandra#153]
The handbook at https://planetcassandra.org/meetup-organizer-handbook/  needs to be removed.  

This needs to exist on cassandra.apache.org, it is something that needs to be officially from the project.

**Comment by StefanVinica** [comment]
This has been removed, if you provide me with the link to the official handbook I can link it

**Comment by StefanVinica** [comment]
@michaelsembwever Ill push an update today on the QA branch and Ill update you for review
