### ISSUE TITLE
Make it clear the news aggregated pages are not content from planet cassandra

### ISSUE THREAD

**Issue by michaelsembwever** [Anant/PlanetCassandra#154]
The aggregated pages like [this](https://planetcassandra.org/news/how-datastax-astra-db-on-microsoft-azure-helps-skypoint-cloud-transform-senior-care/) need to change the "continue reading" link text to something that informs the reader the content is from a different website, and they will be taken there in a new window/tab.

**Comment by StefanVinica** [comment]
https://github.com/Anant/PlanetCassandra/pull/161

**Comment by michaelsembwever** [comment]
Looks good,
